### ISSUE TITLE
Fails at cmake on Windows

### ISSUE THREAD

**Issue by Abby-Sun** [edgeimpulse/firmware-pi-rp2040#7]
I got an issue while making .uf2 on Windows CMD. And it fails at "cmake -G "NMake Makefiles" .."

C:\Pico\firmware-pi-rp2040-main\build>cmake -G "NMake Makefiles" ..
PICO_SDK_PATH is C:/Pico/pico-sdk
PICO platform is rp2040.
CMake Error at ThirdParty/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/CMakeLists.txt:17 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

-- Configuring incomplete, errors occurred!
See also "C:/Pico/firmware-pi-rp2040-main/build/CMakeFiles/CMakeOutput.log".

**Comment by micropicostack** [comment]
This is an issue with selecting the makefile generator, I think by default on Windows it will try to use NMake (Visual Studio??). You have to manually state the generator that you use. 

If you use VS Code and CMake extension then you could  add  `"cmake.generator": "MinGW Makefiles",` to `settings.json` file
